config/routes.rb
Rails.application.routes.draw do
  resources :character_locations
  root "images#index"
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character_location.rb
class CharacterLocation < ApplicationRecord
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :character_locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_locations_controller.rb
class CharacterLocationsController < ApplicationController
  before_action :set_character_location, only: %i[ show edit update destroy ]

  # GET /character_locations or /character_locations.json
  def index
    @character_locations = CharacterLocation.all
  end

  # GET /character_locations/1 or /character_locations/1.json
  def show
  end

  # GET /character_locations/new
  def new
    @character_location = CharacterLocation.new
  end

  # GET /character_locations/1/edit
  def edit
  end

  # POST /character_locations or /character_locations.json
  def create
    @character_location = CharacterLocation.new(character_location_params)

    respond_to do |format|
      if @character_location.save
        format.html { redirect_to @character_location, notice: "Character location was successfully created." }
        format.json { render :show, status: :created, location: @character_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_locations/1 or /character_locations/1.json
  def update
    respond_to do |format|
      if @character_location.update(character_location_params)
        format.html { redirect_to @character_location, notice: "Character location was successfully updated." }
        format.json { render :show, status: :ok, location: @character_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_locations/1 or /character_locations/1.json
  def destroy
    @character_location.destroy
    respond_to do |format|
      format.html { redirect_to character_locations_url, notice: "Character location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_location
      @character_location = CharacterLocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_location_params
      params.require(:character_location).permit(:coordinates, :character_img_file, :image_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  # GET /images or /images.json
  def index
    @images = Image.all

    render json: @images
  end

  # GET /images/1 or /images/1.json
  def show
    @image = Image.find_by(id: params[:id])

    render json: @image
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_locations_helper.rb
module CharacterLocationsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/character_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Character Locations</h1>

<table>
  <thead>
    <tr>
      <th>Coordinates</th>
      <th>Character img file</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_locations.each do |character_location| %>
      <tr>
        <td><%= character_location.coordinates %></td>
        <td><%= character_location.character_img_file %></td>
        <td><%= character_location.image_id %></td>
        <td><%= link_to 'Show', character_location %></td>
        <td><%= link_to 'Edit', edit_character_location_path(character_location) %></td>
        <td><%= link_to 'Destroy', character_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character Location', new_character_location_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgTagger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>